### ISSUE TITLE
Views of custom actions don't include helpers anymore after rails 5.1 upgrade

### ISSUE THREAD

**Issue by andyentity** [sferik/rails_admin#2965]
After upgrading from rails 5.0.3 to 5.1.4 I found that the use of any helper method defined in `app/helpers`  raise a `NoMethodError` or a `NameError` (e.g. `undefined local variable or method `xyz'`). It seems that the default helper classes are not included in the views anymore. Even if I include them explicitly inside the controller they do not become available.

**Comment by mshibuya** [comment]
Sounds like not related to RailsAdmin...
